<?php

/**
 * @file
 * The citations module generates a well-formatted "References" section
 * from citations added in-line while authoring content.
 */

/**
 * Implementation of hook_help().
 *
 * Throughout Drupal, hook_help() is used to display help text at the top of
 * pages. Some other parts of drupal pages get explanatory text from these hooks
 * as well. We use it here to provide a description of the module on the
 * module administration page.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function citations_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      // This description is shown in the listing at admin/modules.
      return t('Insert automatically numbered footnotes using &lt;fn&gt; or [fn] tags.');
  }
}

/**
 * Implements hook_init().
 *
 * TODO Make this conditional by page/configurable.
 */
function citations_init() {
  drupal_add_library('citations', 'citations');
}

/**
 * Implements hook_library().
 */
function citations_library() {
  $libraries['underscore'] = array(
    'title' => 'Underscore.js',
    'website' => 'http://documentcloud.github.com/underscore/',
    'version' => '1.3.1',
    'js' => array(
      drupal_get_path('module', 'citations') . '/underscore-min.js' => array(),
    ),
  );
  $libraries['backbone'] = array(
    'title' => 'Backbone.js',
    'website' => 'http://documentcloud.github.com/backbone/',
    'version' => '0.9.2',
    'js' => array(
      drupal_get_path('module', 'citations') . '/backbone-min.js' => array(),
    ),
    'dependencies' => array(
      array('citations', 'underscore'),
    ),
  );
  $libraries['citations'] = array(
    'title' => 'Citations.js',
    'version' => '0.0.1',
    'js' => array(
      drupal_get_path('module', 'citations') . '/citations.js' => array(),
    ),
    'dependencies' => array(
      array('citations', 'backbone'),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_block_info
 */
function citations_block_info() {
  $blocks['citations'] = array(
    'info' => t('Citations'),
    'status' => TRUE,
    'region' => 'content',
    'weight' => 10,
    'visibility' => 0,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function citations_block_view($delta = '') {
  switch ($delta) {
    case 'citations':
      $block['content'] = "<references>";
      return $block;
  }
}

?>